# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/icdpy',
                'doc_host': 'https://msicilia.github.io',
                'git_url': 'https://github.com/msicilia/icdpy',
                'lib_path': 'icdpy'},
  'syms': {'icdpy.core': {'icdpy.core.foo': ('core.html#foo', 'icdpy/core.py')}}}